### PR TITLE
feat: support scala 3

### PR DESCRIPTION
**Pull request by efgpinto**
Refs #2133 

This PR:
 - adds cross-compilations for the modules required to offer scala 3 support for scala protocol-first sdk 
 - bumps samples to scala 3.3.3 by default
 - configs CI to run all samples both with scala 2.13 and scala 3 so we keep them compatible with both versions

### CODE REVIEW

File: build.sbt [hunk 1]
```diff
@@ -384,7 +394,8 @@ def githubUrl(v: String): String = {
 lazy val devTools = devToolsCommon(
   project
     .in(file("devtools"))
-    .settings(name := "kalix-devtools", scalaVersion := Dependencies.ScalaVersion))
+    .settings(name := "kalix-devtools", scalaVersion := Dependencies.ScalaVersion,
+      crossScalaVersions := Seq(Dependencies.ScalaVersion, Dependencies.Scala3Version)))
```
Comment (octonato) [inline build.sbt:398]:
```suggestion
      crossScalaVersions := CrossScalaVersions))
```

File: build.sbt [hunk 2]
```diff
@@ -323,6 +332,7 @@ lazy val scalaSdkProtobuf = project
       "protocolMinorVersion" -> Kalix.ProtocolVersionMinor,
       "scalaVersion" -> scalaVersion.value,
       "akkaVersion" -> Dependencies.AkkaVersion),
+    crossScalaVersions := Seq(Dependencies.ScalaVersion, Dependencies.Scala3Version),
```
Comment (octonato) [inline build.sbt:335]:
```suggestion
    crossScalaVersions := CrossScalaVersions),
```

File: build.sbt [hunk 3]
```diff
@@ -85,6 +93,7 @@ lazy val javaSdkProtobuf = project
       "scalaVersion" -> scalaVersion.value,
       "akkaVersion" -> Dependencies.AkkaVersion),
     buildInfoPackage := "kalix.javasdk",
+    crossScalaVersions := Seq(Dependencies.ScalaVersion, Dependencies.Scala3Version),
```
Comment (octonato) [inline build.sbt:96]:
```suggestion
    crossScalaVersions := CrossScalaVersions),
```

File: build.sbt [hunk 4]
```diff
@@ -58,6 +65,7 @@ lazy val coreSdk = project
     crossPaths := false,
     Compile / javacOptions ++= Seq("--release", "11"),
     Compile / scalacOptions ++= Seq("-release", "11"),
+    crossScalaVersions := Seq(Dependencies.ScalaVersion, Dependencies.Scala3Version),
```
Comment (octonato) [inline build.sbt:68]:
```suggestion
    crossScalaVersions := CrossScalaVersions,
```

File: project/Dependencies.scala [hunk 5]
```diff
@@ -14,8 +14,10 @@ object Dependencies {
   }
 
   // changing the Scala version of the Java SDK affects end users
-  val ScalaVersion = "2.13.14"
+  val CrossScalaVersions = Seq("2.13.14", "3.3.3")
+  val ScalaVersion = CrossScalaVersions.head
   val ScalaVersionForTooling = "2.12.19"
+  val Scala3Version = "3.3.3"
```
Comment (octonato) [inline project/Dependencies.scala:20]:
```suggestion
```
Can be removed if we use `CrossScalaVersions`

File: sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/TraceContext.java [hunk 6]
```diff
@@ -17,7 +15,7 @@ public interface TraceContext {
    *
    * @return the trace context as an OpenTelemetry context.
    */
-  Context asOpenTelemetryContext();
+  io.opentelemetry.context.Context asOpenTelemetryContext();
```
Comment (octonato) [inline sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/TraceContext.java:18]: any particular reason for not using the import?

File: sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala [hunk 7]
```diff
@@ -85,8 +83,9 @@ class DiscoveryImpl(
 
     // possibly filtered or hidden env, passed along for substitution in descriptor options
     val env: Map[String, String] = system.settings.config.getAnyRef("kalix.discovery.pass-along-env-allow") match {
-      case false => Map.empty
-      case true  => sys.env
+      // FIXME: how to do this better?
+      case obj if !obj.asInstanceOf[Boolean] => Map.empty
+      case obj if obj.asInstanceOf[Boolean]  => sys.env
```
Comment (octonato) [inline sdk/java-sdk-protobuf/src/main/scala/kalix/javasdk/impl/DiscoveryImpl.scala:88]: This is indeed weird. 

What about this? 

```suggestion
      case bool: Boolean => if (bool) sys.env else Map.empty
```

It still feels awkward in pattern matching, but more concise.

**Review by octonato — COMMENTED** [review]
Looking good

Left some minor nitpicking and suggestion.

**Comment by efgpinto** [comment]
Ok, this is looking good now but before I look at the last bits and do some clean-up.. question: should we cross-compile all samples to scala 2.13 and 3? should we have them on scala 3 by default? or should we have only a separate scala 3 sample? I'm inclined to have them all on scala 3 by default but still compile with 2.13 on CI, to make sure we stay compatible. Thoughts?

**Comment by ennru** [comment]
> I'm inclined to have them all on scala 3 by default but still compile with 2.13 on CI, to make sure we stay compatible.

SGTM.

File: build.sbt (hunk 1 above)
Comment (efgpinto) [reply build.sbt]: see current version

File: sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/TraceContext.java (hunk 6 above)
Comment (efgpinto) [reply sdk/java-sdk-protobuf/src/main/java/kalix/javasdk/TraceContext.java]: not warranted after all, reverted

File: project/Dependencies.scala (hunk 5 above)
Comment (efgpinto) [reply project/Dependencies.scala:19]: Not sure I fully understood your suggestion.. you would rather have the version directly on the `CrossScalaVersions` val? see what you think of current setup anyway.

File: .github/workflows/ci.yml [hunk 8]
```diff
@@ -786,4 +811,5 @@ jobs:
           cd samples/${DIR}
           echo "==== Verifying that generated unmanaged sources compile ===="
           rm -rf src/main/scala src/test/scala src/it/scala
-          sbt  --client -Dkalix-sdk.version=$SDK_VERSION Test/compile
+          sbt  --client -Dkalix-sdk.version=$SDK_VERSION '++$SCALA_213_VERSION! Test/compile'
```
Comment (octonato) [inline .github/workflows/ci.yml]: Instead of calling sbt twice, we can use +Test/compile.

Comment (octonato) [reply .github/workflows/ci.yml]: Above, we have to compile steps for each scala version, here we have only one. Not big issue, but we could eventually merge the two other compile steps into one as well. 

The advantage to have then apart is that we make it easier for us to see if it's a Scala 2.13 or 3 compilation error.

File: project/Dependencies.scala (hunk 5 above)
Comment (octonato) [reply project/Dependencies.scala:19]: Looks good now. 

Either

```scala
val ScalaVersion = "2.13.14"
val Scala3Version = "3.3.3"
val CrossScalaVersions = Seq(ScalaVersion, Scala3Version)
```

or

```scala
val ScalaVersion = CrossScalaVersions.head
val CrossScalaVersions = Seq("2.13.14", "3.3.3")
```

I don't remember how it was before, but looks good now.

File: samples/scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala [hunk 9]
```diff
@@ -96,7 +96,7 @@ class CounterServiceIntegrationSpec
       counter.value shouldBe 15
 
       // verify message published to topic
-      val Message(decEvent, md): Message[Decreased] = eventsTopic.expectOneTyped
+      val Message(decEvent, md) = eventsTopic.expectOneTyped[Decreased]
```
Comment (octonato) [inline samples/scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala:99]: Is this changed due to Scala 3? If so, then it's a good plan to move all samples to Scala 3. Scala 3 compiler being more strict, we want to catch possible issues earlier.

File: samples/scala-protobuf-transfer-workflow-compensation/src/main/scala/com/example/transfer/api/TransferWorkflow.scala [hunk 10]
```diff
@@ -40,7 +40,7 @@ class TransferWorkflow(context: WorkflowContext) extends AbstractTransferWorkflo
   override def definition: AbstractWorkflow.WorkflowDef[TransferState] = {
 
     val withdraw = step("withdraw")
-      .asyncCall { withdraw: Withdraw =>
+      .asyncCall { (withdraw: Withdraw) =>
```
Comment (octonato) [inline samples/scala-protobuf-transfer-workflow-compensation/src/main/scala/com/example/transfer/api/TransferWorkflow.scala:43]: Are the `( )` needed?

**Review by octonato — APPROVED** [review]
LGTM

Left a few comments, but nothing major. Fine to merge as is.

File: samples/scala-protobuf-transfer-workflow-compensation/src/main/scala/com/example/transfer/api/TransferWorkflow.scala (hunk 10 above)
Comment (efgpinto) [reply samples/scala-protobuf-transfer-workflow-compensation/src/main/scala/com/example/transfer/api/TransferWorkflow.scala:43]: yes, scala 3 requires those

File: samples/scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala (hunk 9 above)
Comment (efgpinto) [reply samples/scala-protobuf-eventsourced-counter/src/test/scala/com/example/CounterServiceIntegrationSpec.scala:99]: it is indeed required by scala 3.

File: .github/workflows/ci.yml (hunk 8 above)
Comment (efgpinto) [reply .github/workflows/ci.yml]: yeah, that's the reason I kept those apart.. and I thought this one was less likely to present issues so kept it together. But maybe I can also consider merging the other ones.

Comment (efgpinto) [reply .github/workflows/ci.yml]: actually I think I need to call sbt twice here..  or otherwise would need to set `crossScalaVersions := ...` on the same sbt command so that the `+Test` has multiple versions to go through.
